### ISSUE TITLE
hashed filename locales?

### ISSUE THREAD

**Issue by javierguzman** [i18next/react-i18next#1002]
Hello all,

Sorry for asking this here but I did not get any response on Stackoverflow:

The other day I was thinking on Webpack and realized that if I change my translations, user´s browsers are not going to realize. Right now I use the same filename for my translations (e.g. auth.json) and these will be cached presumably.

I use the copy webpack plugin in order to copy and paste my locales into my dist folder. This plugin allows me to create filenames with a hash ( e.g. auth.somehash.json). The question is, how then do I use these files in my code?

Right now in my backend configuration I use:
```
  backend: {
      loadPath: 'assets/locales/{{lng}}/{{ns}}.json',
      addPath: 'assets/locales/{{lng}}/{{ns}}.missing.json'
    },
```
But this would not be anymore applicable as it should be something like {{ns}}.{{somehash}}.json'

Also in my code I translate some stuff like t('auth:stringtotranslate'), so auth would not be anymore applicable. It would be something like t('auth.somehash:stringtotranslate')

Is there any way to achieve what I want to do? Maybe I18next-react somehow notices translation changes and I do not need to do anything.

Thank you in advance and regards.

**Comment by jamuhl** [comment]
I would say - this is not really an issue in production. Your translation files are hosted on a server and at least in most cases you should be able to set cache headers, expires, ... like you need them...

But like you say you can have a loadPath like `{{ns}}.{{somehash}}.json` this does not change the namespace so the `t` call still stays `t('auth:stringtotranslate')` as the ns still is `auth`.

In case of the xhr-backend the load patch can be a function: https://github.com/i18next/i18next-xhr-backend#backend-options `function(lngs, namespaces) { return customPath; }` so that should help wiht adding the hash into your path?

**Comment by javierguzman** [comment]
Hello Jan!

Thanks for your response as always. So the idea would be to use that function(lngs, namespaces) rather than a "fixed pattern" like {{ns}}.{{somehash}}, is that right? I guess that being able to load the path with a function will help a ton.

**Comment by jamuhl** [comment]
the function is a simple way to get a path containing the additional hash...

**Comment by javierguzman** [comment]
Hello again Jan,

All right. Then, I will it a go when I am get closer to production. I am one man army right now :( and I prefer to focus on the core features of the app I am building. i18next is working as it is now so better not to break it! 

Again thank you as always. I close this though I will write back in future to let you know the outcome.
