### ISSUE TITLE
Translate function rename

### ISSUE THREAD

**Issue by zorgick** [i18next/react-i18next#1059]
Hi! Thank you for i18n utility. It helps me a lot!

I'm just curious, why you removed a possibility to change default translate function name? Your utility had this option in v3.1.16 where one could set in i18n config object. But then you removed it in some release.

I'm asking, because there is currently a holy war on this topic in my team, whether we should change it by object spread assignment like `{t: translate} = this.props` in each component or leave as it is. 

My point is that you didn't give us this possibility in the configuration object, so any approach that is in favor of renaming it is contradictory to the author's (yours) intent.

I need your opinion as the developer of this utility

**Comment by jamuhl** [comment]
At some point we had to decide for one of those two options....as we started with `t` -> using `i18n.t` instead of `internationalization.translate` everywhere ;)

The option was removed to keep it consistent with i18next, i18next-parser, ... having a fixed default just makes it easier to use by everyone...using something short makes it more practical
