### ISSUE TITLE
useTranslation() does not react correctly to namespace changes

### ISSUE THREAD

**Issue by red13xxx** [i18next/react-i18next#1064]
**Describe the bug**
useTranslation() returns wrong translation method after namespace change.

**Occurs in react-i18next version**
Tested in 11.3.3

**To Reproduce**
Example React-App using changing namespaces in props.
```
import React, {useEffect, useState} from 'react';
import {initReactI18next, useTranslation} from "react-i18next";
import i18n from "i18next";

i18n
    .use(initReactI18next) // passes i18n down to react-i18next
    .init({
        resources: {
            en: {
                ns1: {name: "namespace1"},
                ns2: {name: "namespace2"},
                ns3: {name: "namespace3"}
            }
        },
        lng: "en"
    });

function App() {
    const [ns, setNs] = useState();
    return (
        <div className="App">
            <a onClick={() => setNs("ns1")}>Ns1</a><br/>
            <a onClick={() => setNs("ns2")}>Ns2</a><br/>
            <a onClick={() => setNs("ns3")}>Ns3</a><br/><br/>

            {ns && <NamespaceName ns={ns}/> }
        </div>
    );
}

function NamespaceName(props) {
    const {t, i18n} = useTranslation(props.ns);

    useEffect(() => {
        //Manually emitting a languageChanged-Event would work around this problem
        //i18n.emit("languageChanged");
    }, [props.ns]);

    return <span>{props.ns + ": " + t("name")}</span>;
}

export default App;
```

1. Start this App
2. Click on "Ns1"
3. Text: "Ns1: namespace1" appears.
4. Click on "Ns2"
5. Text: "Ns2: namespace1" appears.

**Expected behaviour**
The text should be "Ns2: namespace2"

**Workaround**
A workaround is to trigger a re-render with emiting a event when the namespace changes:

```
    useEffect(() => {
        //Manually emitting a languageChanged-Event would work around this problem
        i18n.emit("languageChanged");
    }, [props.ns]);
```

**Problem**
The useTranslation-Hook saves the method in a state. There is a useEffect implemented listening on namespace changes, but it never sets the state, if the namespace is already loaded.

**Comment by jamuhl** [comment]
what's the use case of changing the namespace inside a component during runtime...??!

**Comment by red13xxx** [comment]
I am importing languagebundles from a content management system and referencing them by different namespaces. So selecting different content results in different namespaces. Maybe there is a better way of solving this, but I feel like the behavior described above is not correct nevertheless.

**Comment by jamuhl** [comment]
Having multiple namespaces is what it is about...but I still don't see your use case. What is the component `NamespaceName` good for...it demonstrates you can't change namespace during runtime - but that's actually at least of my knowledge never needed - as structure is like:

```js
function ComponentA() {
    const {t} = useTranslation('ns1');

    return <span>{t("name")}</span>;
}

function ComponentB() {
    const {t} = useTranslation('ns2');

    return <span>{t("name")}</span>;
}
```

**Comment by red13xxx** [comment]
I try to get more specific:
I have a CMS containing different Cities. Each City has a key e.g. "hamburg_de" and resourcebundles containing the keys "name", "information" for different languages.
I add these resourcebundles under the namespace "hamburg_de". 
Now I have a component rendering the name and info of a city:

```
function City(props) {
    const {t} = useTranslation(props.city.key);
    
    return (
        <div>
            <span>{t("name")}</span>
            <span>{t("info")}</span>
        </div>
    )
}
```

So changing the props of this component results in a change of namespace at runtime.

**Comment by jamuhl** [comment]
A namespace for every city...I would expect a namespace `cities` where you get values of hamburg by key `t('hamburg.name');` => instead of adding resourceBundle per object adding https://www.i18next.com/overview/api#addresources

**Comment by stephanpelikan** [comment]
I also run into this problem (using version 11.16.2). My use-case is that I have separate resources per app-section:

1. 'app': Welcome-section
2. 'administration': Administration tasks overview
3. 'administration/onboarding': Onboarding of new users
4. etc.

In the headline of the application I want to visualize the section currently shown. So, every i18n-resource also has key's like 

1. 'app':
"title.long": 'My awesome application',
"title.short": 'MyApp',
2. 'administration':
"title.long": 'Administration',
"title.short": 'Admin',
3. 'administration/onboarding':
"title.long": 'Member applications',
"title.short": 'Applications',
4. etc.

The headline component looks like this:
`
const Headline = () => {
  const { state } = useContext(AppState);
  const { t, i18n } = useTranslation(state.title);
  
  // see https://github.com/i18next/react-i18next/issues/1064
  useEffect(() => {
    //Manually emitting a languageChanged-Event would work around this problem
    i18n.emit("languageChanged");
  }, [ state.title ]);

  return <div>{ t('title.long') }</div>;
`
When I change state.title as part of changing the application's section (e.g. due to routing, etc.) I see the `state.title` changed but `useTranslation(state.title)` still points to the former resource. Only using the workaround as shown above (useEffect) forces to get the updated function t pointing to the resources according to state.title.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#11172

should work out of the boxxin latest version

**Comment by stephanpelikan** [comment]
I can confirm that after switching to 11.17.3 the change of the namespace works without the mentioned workaround!
