### ISSUE TITLE
SSR/SSG with Next.js or how to tell react-i18next which language to render at build time

### ISSUE THREAD

**Issue by MarkWestside** [i18next/react-i18next#1238]
Hello everyone,

When I was looking for a way to use i18n, I did try next-i18next and had a couple of issues. react-i18next did work much better and I could start with little setup.
However, I just noticed, that the translations are not loaded during build time and to search engines will get the default language content for all pages.

Is there a way to get this done? My understanding is, that next-i18next is getting an update because of the latest Next.js version. So I think it is better to stick with react-i18next.

So to not be completely off-issue-type, I think it would be nice to include a sample or short documentation to use react-i18next with Next.js.

Or is it possible to tell `useTranslation()` which language to use at build time and I am missing something?

**Comment by jamuhl** [comment]
That's why next-i18next exists -> it's the way to use react-i18next with next (documented and with samples). If it would be super simple and solved here there would be no reason for next-i18next to exist.

So if you like to solve it with only react i18next you might have to look at next-i18next and see how they do it -> important part is how to preload all needed translations before rendering serverside.

**Comment by MarkWestside** [comment]
Alright, I’ll have another look then. I noticed that there is already a v10 beta, with which I’ll might have more luck.
Thanks.

**Comment by MarkWestside** [comment]
@jamuhl I had zero problems with the latest beta of next-i18next (8.0.0-beta.3).
Thanks again.
