### ISSUE TITLE
transKeepBasicHtmlNodesFor 'b' does not work. However for 'strong' it does work

### ISSUE THREAD

**Issue by FBosler** [i18next/react-i18next#1240]
## 🐛 Bug Report

When using the Trans component with the following config:
```
  react: {
      transSupportBasicHtmlNodes: true,
      transKeepBasicHtmlNodesFor: ['br', 'strong', 'i', 'b'], // don't convert to <1></1> if simple react elements
  },
```
I would expect the following 
```
{
    "anti": {
        "intro": {
            "html": "<p>Antiproportionale Zuordnungen sind <strong>produktgleich</strong>. Mit der <b>Antiproportionalitätskonstante</b> (Bauarbeiter * Dauer) kann man herausfinden, ob eine Zuordnung antiproportional ist. Dieser Wert (hier: {{_distance}}) wird <strong>Antiproportionalitätskonstante</strong> genannt.</p>"
        }
    }
}
```

To work for the `strong` tags, but also the `b` text. However, the `b` tags are not getting the proper formatting, but simply showing the actual tag.

```
<Trans t={t} i18nKey="anti.intro.html" values={{ _distance }}/>
```

## To Reproduce
See steps above

## Expected behavior

Would expect `b`-tags to work just like `strong`-tags

## Your Environment

- *next-i18next*: ^8.0.0-beta.2,
- *os*: macOS Catalina, 10.15.7

**Comment by jamuhl** [comment]
Not sure what's the cause - can be the HTML parser or JSX...idk. PR welcome - workaround use strong which is recommended to be used instead of b anyway.

**Comment by FBosler** [comment]
@jamuhl thx for the quick response. It looks like I am at fault here. It appears that the defaults for `transKeepBasicHtmlNodesFor` are being used (i.e. `strong` still works even after removing it). So maybe I am loading the config wrongly, will look deeper.

Is `transSupportBasicHtmlNodes` enabled by default?

Cheers

**Comment by jamuhl** [comment]
settings should work when using initReactI18next: https://github.com/i18next/react-i18next/blob/master/src/context.js#L50

**Comment by ParallelUniv3rse** [comment]
I've bumped into the same problem with `<i>` elements and managed to locate the issue. 
@jamuhl Could we reopen this issue? 

The problem lies in the `nodesToString` function when `childChildren` for the given element is sometimes an array of one string instead of a string directly. 
This makes [this check](https://github.com/i18next/react-i18next/blob/4839b63e349acfeb17e03a30500c031e494e2908/src/Trans.js#L67) fail because of the typeof condition and is dropped into the following else statement.
