### ISSUE TITLE
Allow multiple type module declarations for different namespaces

### ISSUE THREAD

**Issue by raynor85** [i18next/react-i18next#1257]
## 🚀 Feature Proposal

At the moment the suggested way to add type overload to translations is the following:

https://github.com/i18next/react-i18next/blob/master/example/react-typescript4.1/namespaces/%40types/react-i18next/index.d.ts

Now let's suppose I have 2 different apps, and each of them has different translations defined by a distinct namespace. To add type safety to them, I need to globally import both their resources in a common place. Ideally I'd like for each app to have a distinct setup, for example:

in the root of `app1`
```
// src/app1/index.d.ts
import 'react-i18next';
import { resources1 } from './config';

declare module 'react-i18next' {
  type DefaultResources = typeof resources1['en'];
  interface Resources extends DefaultResources {}
}
```

in the root of `app2`
```
// src/app2/index.d.ts
import 'react-i18next';
import { resources2 } from './config';

declare module 'react-i18next' {
  type DefaultResources = typeof resources2['en'];
  interface Resources extends DefaultResources {}
}
```

If I do that, one app type will override the other. It would be good to allow types to be added by each app independently.

## Motivation

Division of concern and modularity

**Comment by pedrodurek** [comment]
Hey @raynor85, in cases where you have multiple applications in a single repo, it's usually recommended to have a base tsconfig file, and another one for each application. By using this approach, you can define different files declaration per application. I'm going to create an example and post it here.

**Comment by pedrodurek** [comment]
Hey @raynor85, I created an example for your case here https://github.com/i18next/react-i18next/pull/1265. I created the PR as a draft because I'm not sure if it's interesting merging it, since it's a very peculiar case. For big applications mostly, you can drastically improve the runtime performance by using [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html) (apart from having distinct type definitions per sub-applications). You can find more information [here](https://github.com/microsoft/TypeScript/wiki/Performance#using-project-references) as well.
