### ISSUE TITLE
npm build remove in npm 7. Install does not execute build scripts

### ISSUE THREAD

**Issue by Ashpabb** [i18next/react-i18next#1292]
## 🐛 Bug Report

NPM `build` is removed in version 7. During install with NPM 7, the package no longer functions because the build script do not run.

## To Reproduce

Install NPM 7
`npm install react-i18next`

confirm there is no `dist` folder

## Expected behavior

Expect a `dist` folder to be in the `node_modules` `react-i18next` install directory.

## Your Environment

- *runtime version*: node v14, npm v7
- *i18next version*: 11.8.13
- *os*: Mac

**Comment by adrai** [comment]
the build script was never executed on install
the dist folder is included in the npm package

**Comment by Ashpabb** [comment]
@adrai, that makes sense now why my forked would've failed while making new versions and testing. This seems like unexpected behavior for a fork to fail to install properly simply due to npm update. Thoughts? It's not a great experience as a potential contributor to need to lock to a previous version of npm - it appears the `build` command is automatically executed on npm v6 during `install`, according to documentation and my current experience.

**Comment by adrai** [comment]
even if build would have been executed (what it does NOT), it would not make sense, because the dist folder is included in the npm package....

Please create a reproducible example showing the issue....
I'm not able to reproduce it

**Comment by Ashpabb** [comment]
Sure thing, sorry - I should've been more complete with my reproduction steps.

This issue is specifically for running an install from a remote repo like a fork using this syntax:

`npm install <git remote url>`:

I've made an [example repo here.](https://github.com/Ashpabb/react-i18next-npm-example)

Note, I've included the full result of my reproduction in this repo, including the node_modules folder to demonstrate
as well as a `command.sh` which includes the commands I ran to reproduce this issue.

**Comment by adrai** [comment]
This is not a change of npm 7.
The build script was also not automatically executed in npm 6.

May I ask what the reason is to install it via github instead of the official npm?

---

I could think of adding the prepare script like this:
![image](https://user-images.githubusercontent.com/1086194/114260426-2010fc80-99d5-11eb-96d6-e4f0e33226d3.png)


But we (@jamuhl) would need to observe how this behaves on npm publish when creating new versions...
![image](https://user-images.githubusercontent.com/1086194/114260418-0f608680-99d5-11eb-8ac9-787ac25339a5.png)

**Comment by jamuhl** [comment]
not 100% why this is needed...if you prefer maintaining your own fork - this change can be made in the fork?!?
