### ISSUE TITLE
Declaring a different defaultNS than "translation" allows unexpected cases on t function. [Typescript]

### ISSUE THREAD

**Issue by ImADrafter** [i18next/react-i18next#1302]
## 🐛 Bug Report

Declaring a different defaultNS than "translation" allows unexpected cases on t function.

Related issues: https://github.com/i18next/react-i18next/issues/1301

I think the issue might be related to [this line](https://github.com/i18next/react-i18next/blob/master/ts4.1/index.d.ts#L161
) since 'translation' is hardcored.
## To Reproduce

[codesandbox](https://codesandbox.io/live/h4thw4o?file=/src/App.tsx);

~~~tsx
// i18nConfig

i18n.use(initReactI18next).init({
  defaultNS: "ns1",
  resources: {
  sk: {
    ns1: {
      a: "translated A"
    },
    ns2: {
      b: "translated B"
    },
    ns3: {
      c: "translated C"
    }
  }
} 
});
~~~

~~~tsx
// App.tsx
  const { t } = useTranslation();
  ...
  <h4>{t("c")}</h4> {/* It should not compile */}

~~~

## Expected behavior

When a specifing a different defaultNS than "translation", TS compilation should not allow cases that are not supported by JS implementation.

## Your Environment

- *i18next version*: i.e. 20.2.1
- *react-i18next version*: 11.8.13

**Comment by pedrodurek** [comment]
Hey @ImADrafter, It's not possible to automatically infer the `defaultNS` from `t` function based on the options passed to the `init` function. The workaround available right now is this:
```
const { t } = useTranslation<'ns1'>();
```

Since people have been requesting the ability to override the `defaultNS` (without using the workaround above), I'm going to open a PR this week to accommodate that using type augmentation (the same technique we use to infer keys and return types for t function). For now, let's keep this issue opened.
