### ISSUE TITLE
Change language does not re-render components that are memoized using React.memo

### ISSUE THREAD

**Issue by seenubose** [i18next/react-i18next#1442]
## 🐛 Bug Report

We are using react-i18next package within react library that need to be shared across the applications. We wrap the layout using i18nextprovider and changes the language from the header bar. Functional component  that uses React.memo doesn't trigger re-render when the language got changed.When we manually did a change, then it gets reflected with the new language values. We used React.memo(CompName, (prevProps, nextProps) => JSON.stringify(prevProps) === JSON.stringify(nextProps)) to perform re-render based on the props changes. 

```js
export default React.memo(
  LoremIpsumComponent,
  (prevProps, nextProps) => JSON.stringify(prevProps) === JSON.stringify(nextProps),
);

```

## Expected behavior
When we change the language using i18n.changeLanguage() method need to re-render the components that were memoized.

## Your Environment

- *runtime version*: i.e. node v14, deno, browser chrome
- *i18next version*: i.e. 11.12.0
- *os*: Linux

**Comment by adrai** [comment]
Did you pass t as memo dependency?Like:   `const welcome = useMemo(() => <Trans t={t}>Welcome to React</Trans>, [t]);`

Can you create a reproducible example?

**Comment by jamuhl** [comment]
Isn't that the nature of React.memo

As we use `useState` internal: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L65 my guess is only directly used useState calls on top-level inside the component might work - but who knows - the documentation is not very clear about that: https://reactjs.org/docs/react-api.html#reactmemo

Passing in `t` as props in such components will do the trick - beside that - why even use React.memo (do you really have such huge components that needs to much CPU time for rendering?- never had the need...useMemo for long during calculations does the trick in all cases needed (at least in my apps)

**Comment by luixo** [comment]
I'd like to reopen this issue as I stumbled upon the same problem and found out the root cause.

> Isn't that the nature of React.memo

It's not. If the component inner state is updated - the component should update as well. From the docs:

> If your function component wrapped in React.memo has a [useState](https://reactjs.org/docs/hooks-state.html), [useReducer](https://reactjs.org/docs/hooks-reference.html#usereducer) or [useContext](https://reactjs.org/docs/hooks-reference.html#usecontext) Hook in its implementation, it will still rerender when state or context change.

The problem in my project is that I initiate `i18n` instance in an async function on mount to later set it in `setI18n`. Eventually, the non-memoized components pick that instance in [their useEffect](https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L52-L79) and resubscribe to it, but memoized ones do not pick as `useEffect` is not being called (because neither state nor context is changed).

One of the solutions could be a `I18nProvider` wrapping the app to propagate context change whenever it occurs:
```ts
const [i18n, setI18n] = React.useState<i18n>(getI18n());
React.useEffect(() => {
  createI18nInstanceAndInitialize(props.language).then(setI18n);
}, []);
return (
  <I18nextProvider i18n={i18n}>
    {children}
  </I18nextProvider>
);
```

Can `useTranslation` be rewritten in a way that when i18n from `context.getI18n()` get updated - the whole component get rerendered?

**Comment by jamuhl** [comment]
@luixo looks to me that you run into that warning: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L12

you render before having an i18next instance passed to react-i18next --> which shows you a warning that this is incorrect code

https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L64 useTranslation binds and uses useState...so according to your pasted section from the docs it should work out of the box

Not sure if I do something wrong in that sample: https://codesandbox.io/s/react-i18next-forked-fpdmfg but looks like it works like intended?!?
