### ISSUE TITLE
Frozen application with useSuspense and certain configurations

### ISSUE THREAD

**Issue by Slooowpoke** [i18next/react-i18next#1479]
## 🐛 Bug Report
When react-i18next takes a certain configuration with useSuspense: true, the react app/page freezes with no error or messages.

## To Reproduce

Example of frozen sandbox:
https://codesandbox.io/s/react-i18next-forked-f2p5qg?file=/src/i18n.js:341-345

Fixable by either:
- Toggling useSuspense to false
- Removing the resources configuration

## Expected behavior

The application shouldn't freeze but should show an error for what is going on.

It took me a few hours to realise it was the resources, it would be helpful if there was an error or maybe I missed something in the documentation.

## Your Environment

- browser
- i18next: 21.6.14 
- react-i18next: 11.16.2 
- react: 18.0.0
- linux / firefox and chrome

**Comment by jamuhl** [comment]
That's more or less caused by using resources and a backend - while not using the backend at all. Either remove the backend if only using resources or enable partialLoading (loads namespaces not passed in via resources) like:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/977772/162602734-dbef134d-f325-49d2-83de-ffc6402efbc2.png">

@adrai code runs through

- useSuspense tries to `loadNamespaces` and ends here: https://github.com/i18next/i18next/blob/master/src/i18next.js#L254 (not loading anything - as it is not set to load) 
- next render cycle useSuspence checks `hasLoadedNamespaces` which returns false as there is no data loaded https://github.com/i18next/i18next/blob/master/src/i18next.js#L445 - tries to `loadNamespaces`

I would suggest changing: https://github.com/i18next/i18next/blob/master/src/i18next.js#L448

```js
// were not loading at all -> SEMI SUCCESS
if (!this.services.backendConnector.backend) return true;

// to
if (!this.services.backendConnector.backend || (this.options.resources && !this.options.partialBundledLanguages)) return true;
```

**Comment by adrai** [comment]
i18next v21.6.15 and react-i18next v11.16.3 should fix this
@jamuhl had to do it also in react-i18next => https://github.com/i18next/react-i18next/blob/master/src/utils.js#L99 we may think of removing https://github.com/i18next/react-i18next/blob/master/src/utils.js#L43 function now? or use it only as fallback if not defined in i18next?

**Comment by Slooowpoke** [comment]
Perfect thanks for the quick response. I only encountered the bug because I was transitioning from demo resources in the config to trying to use a backend. I’ll make sure to remove the partial configuration, thanks a ton!

**Comment by jamuhl** [comment]
@adrai Oh...I see...there was a little difference in the additional check done for react-i18next...that was done in 2020...guess it's safe to use the commented code nowadays...https://github.com/i18next/react-i18next/blob/master/src/utils.js#L44

just might add a warning if `!i18n.hasLoadedNamespace`
