### ISSUE TITLE
The `Trans` component does not trigger the `React.Suspense`

### ISSUE THREAD

**Issue by uwinkler** [i18next/react-i18next#1513]
## 🐛 Bug Report

If one uses a backend, the translation are loaded asynchronously. The `useTranslation` respects this behaviour and triggers a `React.Suspense`. However, the `<Trans/>` component does not.

## To Reproduce

Here is a minimal example to reproduce this Effect. If you use `MyComponent` (which uses `Trans`) you see the translation key, not the translation. If you use `MyComponentWithHook` (which uses  the `useTranslation` hook)  you will get a translation.  

https://codesandbox.io/s/dazzling-bush-51wgnz?file=/src/App.tsx

## Expected behavior

The Trans component should trigger the React.Suspense as well.

## Your Environment

See codesandbox.io example.

**Comment by adrai** [comment]
Yes, this is by design: https://react.i18next.com/latest/trans-component
![image](https://user-images.githubusercontent.com/1086194/171990094-ebf694b9-e450-4b13-bdf5-873955033605.jpeg)

**Comment by ryancwalsh** [comment]
I have a related question. 

I'm not trying to get Trans to use Suspense because of asynchronously loading _translation_ files, but I _do_ want to use Suspense because of asynchronously loading data that will get injected into the translations (e.g. the last 4 digits of a credit card number).

https://stackoverflow.com/questions/79055852/how-to-use-react-suspense-for-part-of-a-translation-such-as-with-trans-componen
