### ISSUE TITLE
When using shouldUnescape soft hyphen (&shy;) is not unescaped

### ISSUE THREAD

**Issue by Kolombiken** [i18next/react-i18next#1560]
## 🐛 Bug Report

When using the prop `shouldUnescape` `&shy;` is not unescaped while other HTML entities like `&gt;` are. 

Found [an old issue](https://github.com/i18next/react-i18next/issues/1435) by @nilsmehlhorn that looks like it was closed since it has been fixed. But maybe there has been a regression?

## To Reproduce

A [codesandbox](https://codesandbox.io/s/react-i18next-forked-j3vq2j) example forked from the old issue with updated package versions.

## Expected behavior

Expected output is that `&shy;`is unescaped as a soft hyphen.  

## Your Environment

- *runtime version*: node v16.17.0, Chrome
- *react-i18next version*: 11.18.6
- *i18next version*: 21.9.2

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to extend the existing unit tests.

**Comment by Kolombiken** [comment]
@adrai Yes, maybe. If I can figure out how to fix it. Need to look into it.

**Comment by nilsmehlhorn** [comment]
In the issue #1435 and it's corresponding pull request #1529 you've mentioned it was decided to enable override of the default unescape behavior (which you can see here https://github.com/i18next/react-i18next/blob/d3247b5c232f5d8c1a154fe5dd0090ca88c82dcf/src/unescape.js) rather than adding additional HTML entities.

So, it's now possible to provide a custom unescape function which respects any HTML entities you like - I'm doing this successfully in a project since the PR was merged. Here's a test showing roughly how to put it into config: https://github.com/i18next/react-i18next/blob/a0eed42303bda4863a832cbd8b280d04448f2690/test/trans.render.spec.js#L647

**Comment by Kolombiken** [comment]
@nilsmehlhorn This is great! 🎉 Also a lot better than adding HTML entities to a list. Sorry for not understanding that this was the outcome from that old issue. 

Maybe what could still be done is an update to the documentation with a clear example? I totally missed that this was possible. Anyway. Closing this now.
