### ISSUE TITLE
TS: linting error when using template string with i18next-react v12.0.0 and i18next v22.0.4

### ISSUE THREAD

**Issue by bpc1985** [i18next/react-i18next#1579]
I find this linting error when using with template string i18next-react v12.0.0 and i18next v22.0.4 although it shows correct translations. You can see in this image

![Screenshot 2022-11-09 133947](https://user-images.githubusercontent.com/271786/200822035-05c2e435-a2d8-45fe-ba8a-6d4816119eb1.png)

![Screenshot 2022-11-09 142735](https://user-images.githubusercontent.com/271786/200830423-09432723-ed3c-45dc-91c9-c249cae1422a.png)

Using `{t('lang.en')}` is OK
However, using either {t(`lang.${lang}` as const)} or {t(`lang.${lang}`)} causes linting error

I try to follow new doc https://www.i18next.com/overview/typescript by adding "as const", it does not help also.

**Comment by pedrodurek** [comment]
Hey @bpc1985, `lang` can't be a string, it needs to be a literal value. For example:
```tsx
type Props = {
  lang: 'en' | 'pt';
}

const Comp = ({lang}: Props) => {
  const [t] = useTranslation();

  return <span>{t(`lang.{lang}`)}</span>
}
```

We usually use `as const` to get the literal type of a string (e.g.: `const foo = 'foo' as const`). In your case, you need to narrow down the options using union type (`'en' | 'pt') for `lang`. Otherwise, typescript can't guarantee if that key actually exists.

**Comment by pedrodurek** [comment]
I'm closing this for now, but continue to ask me questions if it's not clear to you.
