### ISSUE TITLE
Support for HTML links readable in translation strings

### ISSUE THREAD

**Issue by oliverwatkins** [i18next/react-i18next#1611]
## 🚀 Feature Proposal

Currently some inline HTML tags are supported with Trans object.

`<p> </strong> hello <strong>  hello </strong>.</p>`

which is great. 

But why can't we also have HTML links? ie `<a href=blah> </a>`
Why can't this support other HTML tags? Is there a technical reason for this?

## Motivation

I have a page with is peppered with links, and it just seems overly complex, and unnecessary, to interpolate all these links using these strange `<1><2>` tags.

**Comment by jamuhl** [comment]
There is a limitation: No html attributes are allowed on those html elements

reason:

- html attibutes do not map to JSX props in all cases (html attributes are lowercased, JSX props camelCased)
- some props differ completely from attributes: eg. styles, events 

so that all has limitations. 

you do not have to use `<0></0><1></1>` in your strings: https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0 you can use named replacements
