### ISSUE TITLE
Request: Enable formatter option also to parse HTML tags 

### ISSUE THREAD

**Issue by SaroGFX** [i18next/react-i18next#1620]
## 🚀 Feature Proposal

To also allow for the formatter to wrap certain words in certain HTML tags (`<b>`, `<u>`, `<i>`).

## Motivation

For consistently and ease-of-use. The `<Trans>` component is confusing. Benefit of having all the formatters in the same space. Easy to use and makes most sense like this.

## Example

`"Key": "Create {{ item, bold }}" `

``` jsx
i18n.services.formatter?.add('bold', (value) => {
  const boldValue = createElement('strong'); 
  return  boldValue.innerHTML = value;
});
````

**Comment by adrai** [comment]
Why exactly not the Trans component?

**Comment by SaroGFX** [comment]
**Why:** The translator should have access to these basic formatting options. Changes should not require a full code deployment from a dev.

Also because that's what I would expect formatting to be able to do, in one way or another. Trans is a weird solution for something so simple a bold tag. Also having <1></1> tags in the keys doesn't give the translator much context on what it does.

The formatters make sense to me, but alternatively, there should be an option to 'allow' certain pure html tags. Like <b>, <u>, <i>, <br>

**Comment by adrai** [comment]
Trans component can also be used with component names instead of index tags: https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0

And simple tags works anyway: https://react.i18next.com/latest/trans-component#usage-with-simple-html-elements-like-less-than-br-greater-than-and-others-v10.4.0
