### ISSUE TITLE
Multiple i18next initialized 

### ISSUE THREAD

**Issue by hilalbuyukgullu** [i18next/react-i18next#1635]
## 🐛 Bug Report

Hello. We have multiple component libraries. All of these libraries use the i18next library. When we add these libraries to our projects, we get a missingKey error.

![image](https://user-images.githubusercontent.com/44446749/234548756-5760af89-1360-4db0-b14f-af29eeed5636.png)

## To Reproduce

i18n.init 

![image](https://user-images.githubusercontent.com/44446749/234549134-6529451e-3114-4705-829a-0e02b8495b5a.png)

## Expected behavior

I expect to be able to multiple initialize

## Your Environment

-  runtime version: node v16.18.0
- *i18next version*:  22.4.14
- *os*:  Windows
- *typescript*:  4.7.4

**Comment by adrai** [comment]
you can create multiple instances like here: https://github.com/i18next/react-i18next/blob/master/example/react-component-lib/src/other-lib/i18n.js#L4
thanks to: https://www.i18next.com/overview/api#createinstance

**Comment by hilalbuyukgullu** [comment]
When I *createInstance*, "i18next: init: i18next is already initialized in libraries. You should call init just once!"  I'm getting the warning. 

![image](https://user-images.githubusercontent.com/44446749/234557871-17e80b3a-8b53-47d0-abdc-88b210b44ac3.png)

**Comment by adrai** [comment]
yes, you still should call init just once, there should be no reason why you need to call init multiple times

**Comment by hilalbuyukgullu** [comment]
@adrai  actually i only use init once 

i18n.init

![image](https://user-images.githubusercontent.com/44446749/234562581-d98a81d9-e469-4b36-932a-a7bc979c170e.png)

the file I exported the methods to

![image](https://user-images.githubusercontent.com/44446749/234562739-2c9485e2-5383-4118-a4a5-960b422ec500.png)

**Comment by adrai** [comment]
if that warning is logged, it means the init function is called multiple times...
Please do not provide just screenshots, but a minimal reproducible example repository.

**Comment by hilalbuyukgullu** [comment]
Unfortunately I cannot create a sample repository. But I can explain in more detail @adrai

**Comment by asezgin58** [comment]
Hi @adrai , the local library is being installed in a different project with the **git clone** method. Many similar local libraries can be added to this project. Each local library also has i18n usage within itself and the init process is run within itself.

Therefore, even if only one init appears in this project, the init process is triggered within the local libraries imported within the project. This run state causes missingKey errors because it sees multiple init processes.

What is your suggestion in this case? Should we merge the resulting instance into the imported projects without running an init process in local libraries, and then trigger an init process like a single instance?

Example usage for local library install with git clone; `npm install git+ssh://git@github.com:user_name/node_project.git`

**Note :** Local library is not published on npm. The library repository is located in the internal network. That's why I shouldn't post anything. I seek your understanding.

**Comment by adrai** [comment]
Sorry, but without a concrete example I really don't understand why the init function is called multiple times.
I see 2 options:
Option 1: use createInstance and pass the resulting appropriate i18n instance via provider or similar where needed...
Option 2: create a setup like this: https://github.com/i18next/react-i18next/blob/master/example/react-component-lib

**Comment by asezgin58** [comment]
Hi @adrai , I got successful results by running the "init" process with a different method independent of all instances, based on the solutions you suggested. In my case, since more than one "init" method needs to be run in a project, I called them in a controlled manner. This solution worked for me. Thanks for your support.

**Custom init method**
`
export const i18nInit = () => { i18n.init() }
`

**Comment by rosskevin** [comment]
Perhaps what is missing here is an explanation or strategy to use multiple library locales.  The solution we came up with is not to use init in multiple libraries, but at the entry point.  We created a webpack loader, and now a vite plugin that loads all the locales into a single bundle (which allows for overrides), and you supply that to the init.

- https://github.com/alienfast/vite-plugin-i18next-loader
- https://github.com/alienfast/i18next-loader/

We are looking towards using nextjs, so we will probably be extracting this loading logic into a separate package for reuse (hopefully).

Take a look at the docs on the vite plugin and see if this might help. Specifically, this is a good hint: https://github.com/alienfast/vite-plugin-i18next-loader#paths-for-overridingwhite-labeling
