### ISSUE TITLE
Is there a way to detect missing interpolation in build-time?

### ISSUE THREAD

**Issue by gbyesiltas** [i18next/react-i18next#1711]
## 🚀 Feature Proposal

Hey guys, I went through the docs and the issues but I couldn't find something like this. I am using React Native and I would like the app to error out on build-time if there is missing interpolation in one of the locales. Is there a way to do this currently? Thank you!

## Motivation

Our translations come automatically from PR's opened by Transifex and I would like to have some certainty that they are correct without going through them manually.

**Comment by adrai** [comment]
During build-time there is nothing I'm aware of (since JavaScript theoretically has no build-time).
During runtime, in the logs you should see something like: "missed to pass in variable ${matchedVar} for interpolating ${str}"
With TypeScript, the check is only made for your source language: https://www.i18next.com/overview/typescript
<img width="654" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/a05c63b9-5f18-4022-b195-e730fd3444b5">

Beside that, if you switch to the [official TMS of i18next](https://www.i18next.com/misc/the-history-of-i18next#locize-to-the-rescue) that sponsors, maintains i18next ([locize](https://locize.com)), there is a check/issue for that, built in: https://docs.locize.com/issues#issue-240-detected-i18n-syntax-inconsistency
