### ISSUE TITLE
How to change language after initialization

### ISSUE THREAD

**Issue by mikkelwf** [i18next/react-i18next#214]
Hi.

I'm trying to change language after init, but it seems to be quite tricky.

Our language is encoded in the url `/lang/foo/bar`, and i've made custom detector to pick that up (That works).
The detector only seems to run on initialization, so i've tried to add a listener to the history api location change (i use react-router with browser history), and the event gets fired okay, and my `i18n.changeLanguage` also seems to work, but the new language is not reflected in the `I18nextProvider`

* Is it not possible to change language after init?
* If so, it would be lovely with an example on how to properly hook up the `I18nextProvider` to make this work.

Thanks in advance.. :)

**Comment by jamuhl** [comment]
do you use the translated hoc? https://github.com/i18next/react-i18next/blob/master/src/translate.js#L62 a change of lng should force a rerender

**Comment by goums** [comment]
Hello,

I'm having the same issue.
I do use the i18n provider and the translate HOC, as shown in the repo example, and have the same configuration.
When I call` i18n.i18n.changeLanguage("en", (err, t) => {...});`
It seems to be working fine as I got following console output:
```
i18next::backendConnector: loaded namespace translation for language en Object {...}
i18next: languageChanged en
```
However, nothing gets rerender...

**Comment by goums** [comment]
It look's like the "i18nLoadedAt" is correctly updated and propagated to the wrapped child, but the translate method is strangely not responding with the updated local.

I've added this line in my translated component:
`{this.props.i18nLoadedAt && this.props.i18nLoadedAt.valueOf()+': '+this.props.t('Hello')}`

At load time, with language set to "en", it shows:
`1481234180090: Hello`

After a call to`i18n.changeLanguage("fr", (err, t) => {...});`, it is rerendered:
`1481234438517: Hello`

You see the timestamp is sooner, "i18nLoadedAt" has been updated, and my component has been rerendered as required.
But however, the translation does not lookup to the "fr" language as it still says "Hello" instead of "Bonjour".

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/commit/0d1d443f0b9170482c052112e73f4bfe663875e3 i extended the example https://github.com/i18next/react-i18next/tree/master/example seems to work at least here.

not sure where your code breaks it?!?

**Comment by jamuhl** [comment]
Closing for now...hope it worked out...if not feel free to reopen.
