### ISSUE TITLE
translate decorator affects styles when using with react-virtualized

### ISSUE THREAD

**Issue by robgev** [i18next/react-i18next#410]
I am using translate() on my react component which is react-virtualized list. After adding this line react-virtualized element start to overlap, etc. 
Seems like translate() does not allow react-virtualized to calculate heights or not show elements or something like that. Here's an example of what happens.
![image](https://user-images.githubusercontent.com/9303680/37716104-20d4dec4-2d37-11e8-8e3f-33a201849b51.png)

**Comment by jamuhl** [comment]
hm...we use react-virtualized on our localization as a service offering https://locize.com but do not get this issue...the `t` function itself is synchronous - so that should not being an issue.

Do you have the translations already loaded at the moment you render that list...or does the list trigger loading an additional namespace?

**Comment by jamuhl** [comment]
Were you able to solve this?

**Comment by jamuhl** [comment]
that is ok. so i will close this for now. thanks for the follow up.
