### ISSUE TITLE
How to add a JSON with translations in Storybook ?

### ISSUE THREAD

**Issue by mlegait** [i18next/react-i18next#428]
Hello,

There is an example showing how to use react-i18next with Storybook (thank you for that 😄) but I don't find how to use a JSON to translate strings. 

We use keys in our components and we would like to have "real strings" in storybook.
In our application, JSONs come from an API. But in storybook, we would like to have an hard-coded JSON file just to replace keys for demo purposes.

Is it possible ? If yes, can you explain me how to do that ?

Thank you very much for your help.

**Comment by jamuhl** [comment]
Sure...

a) having "real strings" instead of keys is done like this: https://www.i18next.com/principles/fallback#key-fallback (hope that sample in the docs make the idea clear...else just ask again for a more information how to do so)

b) normally you got a backend the sample https://github.com/i18next/react-i18next/blob/master/example/storybook/src/i18n.js#L23 shows using it with our service https://locize.com but you also can use the https://github.com/i18next/i18next-xhr-backend xhr-backend.

To load translations hardcoded you can init i18next with options.resources like in the introduction sample here: https://www.i18next.com/overview/getting-started#basic-sample or use the API for adding them after init: https://www.i18next.com/overview/api#addresourcebundle

hope that information helps.

**Comment by mlegait** [comment]
Thank you for your quick answer 😄 

Is there a way to do both ?
Use a backend in production and use an hardcoded file in storybook ?

**Comment by jamuhl** [comment]
if i remember right for react there is something like `process.env.NODE_ENV` to choose between different environments: https://daveceddia.com/multiple-environments-with-react/

Just add resources on init or backend depending on this.

**Comment by mlegait** [comment]
Thank you for your help, I will check.

**Comment by jamuhl** [comment]
guess this can be closed...if not feel free to reopen. Thank you.

**Comment by jingoldby** [comment]
Is there a working example showing loaded translations from json? I am using 
`i18n.use(initReactI18next).init({
  fallbackLng: 'en',
  debug: true
});`

and then passing this i18n instance to <I18nextProvider i18n={i18n} /> but my definitions in public/static/locales/en are not loaded. I've tried addResources and addResourceBundle but must be doing something incorrectly. Any help appreciated!

**Comment by jamuhl** [comment]
@jingoldby https://github.com/i18next/react-i18next/tree/master/example/storybook not sure if it's totally outdated but might be worth a look.
