### ISSUE TITLE
Language parameter as a URL path

### ISSUE THREAD

**Issue by eyal0803** [i18next/react-i18next#494]
I have a Next.js app using an ExpressJS server and I'd like to be able to specify the language parameter (`?lng`) as a URL path, e.g: `example.com/en`.

I saw #463 but I'm not sure how to implement that.

Currently I'm tinkering with the example from Next.js (https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next), so implementations with this example are very much welcome.

Thanks in advance.

**Comment by jamuhl** [comment]
Like described in #463 the express middleware has a detector for this. But not sure how to solve this in next.js (clientside router)...markolofsen might help?

**Comment by eyal0803** [comment]
@jamuhl Why did you close the issue?

**Comment by jamuhl** [comment]
because there is no issue...both the detector in express-middleware (https://github.com/i18next/i18next-express-middleware#language-detection) and the client side detector can take lng from path (https://github.com/i18next/i18next-browser-languageDetector#introduction).

So this is no issue...all can be done

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/example/nextjs_withAppJS/server.js#L17 -> detector server side is added - next line init -> just add options to include the path for detection

https://github.com/i18next/react-i18next/blob/master/example/nextjs_withAppJS/i18n.js#L32 -> clientside detector -> at top there are the options for the clientside detector

so i guess your problem is more how to setup express and next.js to accept routes having lng in path as https://github.com/i18next/react-i18next/blob/master/example/nextjs_withAppJS/server.js#L42 won't work out of the box....right?
