### ISSUE TITLE
Create-react-context v0.2.3 licence terms deny use on certain organizations.

### ISSUE THREAD

**Issue by jkarttunen** [i18next/react-i18next#635]
**Is your feature request related to a problem? Please describe.**
create-react-context v0.2.3 licence prohibits usage of CRC for certain organizations.
Even though the licence terms have been updated, the version has not been incremented and npm servers the old licence version.

**Describe the solution you'd like**
Can we use the latest commit of crc, instead of the npm published one?
Or update Reacti18next licence terms to match CRC licence.

**Describe alternatives you've considered**
Or fork crc and publish on npm.

**Comment by jamuhl** [comment]
https://github.com/jamiebuilds/create-react-context/commit/f31c9edb9a1f93d5e673de5ea8b1e09a46f9b407#r31551322

hopefully we get a version 0.2.4 - would be prefer to just bump that instead of forking.

Alternative would be removing the polyfill and leave that to userland. Will give them some time to publish and if no response will consider that.

**Comment by jamuhl** [comment]
@rhinoceraptor yes that is the fallback plan for v9

**Comment by jamuhl** [comment]
removed create-react-context in react-i18next@9.0.0 -> upgrade of react to v16.3 needed (or polyfill in userland)
