### ISSUE TITLE
Typescript Definition for translate HOC does not work

### ISSUE THREAD

**Issue by TLadd** [i18next/react-i18next#669]
**Describe the bug**
Attempted to update i18next/react-i18next to the latest (had been on a version that was still using types from DefinitelyTyped) and it seems that the translate HOC definition is not working. The follow snippet raises an error, whereas it worked with the @types/react-i18next definition.

```
import React from "react";
import { translate } from "react-i18next";
import i18next from "i18next";

function Foo({ a, t }: { a: string; t: i18next.TranslationFunction }) {
  return <span>{t(a)}</span>;
}

translate()(Foo);
```

```
Argument of type '({ a, t }: { a: string; t: TranslationFunction<any, object, string>; }) => Element' is not assignable to parameter of type 'ComponentType<WithNamespaces>'.
  Type '({ a, t }: { a: string; t: TranslationFunction<any, object, string>; }) => Element' is not assignable to type 'FunctionComponent<WithNamespaces>'.
    Types of parameters '__0' and 'props' are incompatible.
      Property 'a' is missing in type 'WithNamespaces & { children?: ReactNode; }' but required in type '{ a: string; t: TranslationFunction<any, object, string>; }'.ts(2345)
```

**Occurs in react-i18next version**
9.0.2

**Comment by nikolay-borzov** [comment]
Try this
```
interface FooProps extends WithNamespaces {
  a: string
}

function Foo({ a, t }: FooProps) {
  return <span>{t(a)}</span>;
}
```

**Comment by rosskevin** [comment]
Thanks @nikolay-borzov 

@TLadd test here proves it is working - https://github.com/i18next/react-i18next/blob/master/test/typescript/withNamespaces.test.tsx

**Comment by TanninOne** [comment]
@nikolay-borzov @rosskevin Sorry, but I disagree with closing this issue. The fact that withNamespaces/withTranslation provides more properties than t doesn't mean that the component has to use/know about them.
It should be acceptable for a component to only use the t parameter otherwise the coupling between the component and specific versions of react-i18next is tighter than necessary and it complicates user code. Please consider making the properties in WithNamespaces and WithTranslation all optional.

**Comment by rosskevin** [comment]
@TanninOne your comment is unrelated to this issue.  Perhaps you should file a new one.  

If you want any changes you should PR a usage test that breaks indicating why such action would be necessary.  Here are the current usage tests https://github.com/i18next/react-i18next/tree/master/test/typescript

**Comment by TanninOne** [comment]
It's not unrelated, the code in the OP should have worked, period.

"as any" it is... _sigh_

**Comment by rosskevin** [comment]
@tanninone your comment is not constructive. We have tests covering the usage and they prove it works. If you would like to see a usage change I have already provided instructions.

**Comment by nikolay-borzov** [comment]
@TanninOne, this how HOC works in TypeScript. You must provide a type that includes props that HOC adds. Otherwise, how could component know what props it receives from HOC.

**Comment by TanninOne** [comment]
You're completely missing the point of higher order components as a concept.
The idea of HOC is to make components more modular. The OP designs a component Foo that requires a t-function to do its translations. Whether that t function is passed in from the parent component, from a unit test or via react-i18next withTranslation _should not matter in the design_ of Foo.
You shouldn't have to pass in a i18n and tReady when using Foo directly because it doesn't need them!

You're creating typings that essentially enforce that Foo can _only_ be used with withTranslation because now its public interface includes all WithTranslation properties, which may be modified on the next react-i18next update - breaking all unit tests or other use cases of Foo for no good reason.
Foo now _always_ has to be passed i18n and tReady even though they aren't used, just because it _can_ also be used together with the withTranslation HOC.
That's pointless, if Foo was only to be used in this way, what was the point of using a HOC in the first place? You could just define a "TranslatedReactComponent", extended from React.Component, that everyone can derive from. Much less code, much less complicated.

You're putting limitations on user code through the design of your typings that wouldn't be there if it was javascript code.

The fact that you have proven these typings can be made to work does not prove they are correct nor that they are good.

If you find my report not constructive then I'm sorry for wasting everyone's time (my own included) but I am a bit frustrated after spending hours updating perfectly valid and working code just to make it satisfy your typings that make no sense.

**Comment by rosskevin** [comment]
@tanninone you continue to complain yet put forth no PR proposing the changes you purport are correct.

**Comment by nikolay-borzov** [comment]
I see your point. But how should types look in this case? Should `translate()` accept component without restricting props? `translate()` adds `WithNamespaces` props. Not using `WithNamespaces` means - "I don't care what this HOC does, but I hope it matches the interface of my component"

As for tests, I wrote a little helper:
```
export function getWithNamespacesProps(): WithNamespaces {
  return {
    tReady: false,
    t: (key, options) =>
      // TODO: https://github.com/i18next/react-i18next/pull/665#issuecomment-456053120
      (options ? JSON.stringify({ key, options }) : key) as any,
    i18n
  };
}
```
And use it like this
```
const props: FooProps {
  onFoo: jest.fn(),
  ...getWithNamespacesProps()
}
```
