### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'i18n' of undefined 

### ISSUE THREAD

**Issue by sashberd** [i18next/react-i18next#750]
Hey guys,
I just upgraded my react-i18next and i18next to the latest versions:
"i18next": 15.0.4
"react-i18next": 10.0.2

I use next js in my application also

My init of i18 is: 

```
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';

const startI18n = async (file, lang, axisName) => {

  if (!i18next.isInitialized) {
    await i18next.use(initReactI18next).init({
      lng: lang, // active language http://i18next.com/translate/
      fallbackLng: 'he',
      resources: file,
      ns: ['common', axisName],
      defaultNS: axisName,
      fallbackNS: 'common',
      debug: false,
      interpolation: {
        escapeValue: false, // not needed for react!!
        formatSeparator: '::',
        format: function(value, format, lng) {
          // t('jenia::uppercase')
          if (format === 'uppercase') return value.toUpperCase();
          return value;
        },
      },
      react: {
        useSuspense: false,
        wait: true
      }
    });
  }

  return i18next;
};

export default startI18n;

export const getI18nInstance = () => {
  return i18next;
};

```

The function called from my index.js with next code: 

 ```
<I18nextProvider i18n={getI18nInstance()}>
          <MuiThemeProvider muiTheme={muiTheme}>
            <LayoutWithWidth
              {...this.props}
              direction={getI18nInstance().dir()}
              hideSiteHeader={options.noLayout}
              hideSiteFooter={options.noLayout}>
              <PageContent {...this.props} theme={theme} />
            </LayoutWithWidth>
          </MuiThemeProvider>
        </I18nextProvider>
```
In my application I use material-ui dialogs and after upgrade to lates version **only** in modal-dialogs calls I started to get errors:

> Uncaught TypeError: Cannot read property 'i18n' of undefined
>     at useTranslation (useTranslation.js:12)
>     at I18nextWithTranslation (withTranslation.js:8)
>     at renderWithHooks (react-dom.development.js:12839)
>     at mountIndeterminateComponent (react-dom.development.js:14814)
>     at beginWork (react-dom.development.js:15419)
>     at performUnitOfWork (react-dom.development.js:19106)
>     at workLoop (react-dom.development.js:19146)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:149)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
>     at invokeGuardedCallback (react-dom.development.js:256)
>     at replayUnitOfWork (react-dom.development.js:18372)
>     at renderRoot (react-dom.development.js:19262)
>     at performWorkOnRoot (react-dom.development.js:20136)
>     at performWork (react-dom.development.js:20048)
>     at performSyncWork (react-dom.development.js:20022)
>     at interactiveUpdates$1 (react-dom.development.js:20289)
>     at interactiveUpdates (react-dom.development.js:2170)
>     at dispatchInteractiveEvent (react-dom.development.js:4882)
> useTranslation @ useTranslation.js:12
> I18nextWithTranslation @ withTranslation.js:8
> renderWithHooks @ react-dom.development.js:12839
> mountIndeterminateComponent @ react-dom.development.js:14814
> beginWork @ react-dom.development.js:15419
> performUnitOfWork @ react-dom.development.js:19106
> workLoop @ react-dom.development.js:19146
> callCallback @ react-dom.development.js:149
> invokeGuardedCallbackDev @ react-dom.development.js:199
> invokeGuardedCallback @ react-dom.development.js:256
> replayUnitOfWork @ react-dom.development.js:18372
> renderRoot @ react-dom.development.js:19262
> performWorkOnRoot @ react-dom.development.js:20136
> performWork @ react-dom.development.js:20048
> performSyncWork @ react-dom.development.js:20022
> interactiveUpdates$1 @ react-dom.development.js:20289
> interactiveUpdates @ react-dom.development.js:2170
> dispatchInteractiveEvent @ react-dom.development.js:4882
> index.js:2178 The above error occurred in the <I18nextWithTranslation> component:
>     in I18nextWithTranslation (created by MuiComponent)
>     in MuiComponent (at AuthAndRechargeDialogsContainer.js:277)
>     in div (at AuthAndRechargeDialogsContainer.js:247)
>     in div (created by DialogInline)
>     in div (created by Paper)
>     in Paper (created by DialogInline)
>     in div (created by TransitionItem)
>     in TransitionItem (created by TransitionGroup)
>     in div (created by TransitionGroup)
>     in TransitionGroup (created by DialogInline)
>     in div (created by DialogInline)
>     in DialogInline

e.g: in my contact us dialog form I used withTranslate HOC:

```
import React from 'react';
import { Dialog, IconButton } from 'material-ui';
import FullscreenDialog from 'material-ui-fullscreen-dialog';
import ErrorIcon from 'material-ui/svg-icons/av/not-interested';
import { withTranslation } from 'react-i18next';
import { connect } from 'react-redux';
import compose from 'recompose/compose';


class ContactUsDialog extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {};
  }
render() {
    
    const {
      t,
...OtherLocalProps,
    } = this.props;

 <div >
      
          <Dialog
            autoDetectWindowHeight={false}
            repositionOnUpdate={true}
            autoScrollBodyContent={true}
         
            open={dialogStatus ? !!dialogStatus.isOpen : false}
         
            onRequestClose={this.onClose}
            title={
              <div>
                <div className="login-title" >
                  {t('contact')}
                </div>
                <div className="close-icon-wrapper">
                  <IconButton
                    onClick={this.onClose}>
                    <CloseIcon />
                  </IconButton>
                </div>
              </div>
            }>
              <ContactUsForm
                form={FORM_NAME}
                isRtl={isRtl}
                onError={this.scrollToTop}
                onSuccess={this.scrollToTop}
                initialValues={initialValuesForContactUsForm}
              />
            </div>
          </Dialog>
***next class local functions and constants***
const enhance = compose(
  withTranslation(),
  connect(mapStateToProps, mapDispatchToProps)
);

export default enhance(ContactUsDialog);


```

On pause exception I saw that withTranslation function can not get i18 instance from react dom context
![screen shot 2019-02-21 at 11 37 01](https://user-images.githubusercontent.com/11975561/53158799-26fa0c80-35cd-11e9-9ca4-7996222a72da.png)

Any suggestions to fix this strange issue

**Comment by jamuhl** [comment]
Guess it's using some portal taking the modal out of the regular JSX tree placing it somewhere outside -> so the context won't might / be not there...just my wild guess...

So the issue seems not related to i18next but caused by MaterialUI not supporting context properly on that component.

In combination with next.js were you rely on using I18nextProvider and context to get things working i'm not sure how to solve this properly...eventual additional use of `i18next.use(initReactI18next)` or wrapping that component in an additional inner I18nextProvider might help. Or directly passing i18n as prop into that component...try and error i would say

**Comment by sashberd** [comment]
@jamuhl Thanks for quick reply
We just investigate that the problem is only with Dialog material-ui component, so I think you are right about the issue core. 
Thanks for give a hand

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project 🙏

**Comment by jsomsanith** [comment]
Hi, I post that here because it’s the only issue I found related to my issue.
I had the same issue, with AgGrid, that renders react components outside of the main component tree.

# What happened
- I have an `I18nextProvider`. The new provider set a boolean to indicate that we use the context
```
export function I18nextProvider({ i18n, children }) {
  usedI18nextProvider(true); // HERE
  …
}
```
- I use withTranslation HOC (compatibility with the old translate HOC). Under the hood, it uses the `useTranslation` hook
- `useTranslation` will try to resolve the i18n object via props, context, or global i18n that is set via `i18n.use(initReactI18next)`
Here is the problem, in the hook.
```javascript
export function useTranslation(ns, props = {}) {
  // assert we have the needed i18nInstance
  const { i18n: i18nFromProps } = props;

  // THE PROBLEM IS HERE
  const { i18n: i18nFromContext } = getHasUsedI18nextProvider() ? useContext(I18nContext) : {};

  const i18n = i18nFromProps || i18nFromContext || getI18n(); // the resolution
```

I have a provider, so `getHasUsedI18nextProvider()` returns true. It tries to resolve i18n via context. But the component is outside of main component tree, so `useContext(I18nContext)` returns `undefined`.
Then we have the destructuring. If you try to destructure `undefined` —> boom 💥 

# So what’s next ?
I fix the issue by removing the context. I now rely only on `i18n.use(initReactI18next)` which is necessary to provide i18n config to components outside of the main component tree.

Perhaps you can revive this issue, and convert it to an easy fix for new contributor.

# Last word
BTW, thank you for your work on react-i18next !

**Comment by jamuhl** [comment]
@jsomsanith

This is not specific to react-i18next - every module using context suffers this problem.

My opinion: this is a problem of the components taking elements out of the main tree and not keeping the context working.

Not even sure how you would solve this...there is no way to know if something killed the context by moving stuff out of the main tree.

**Comment by jsomsanith** [comment]
I posted that here, because it’s an easy fix that can be done on react-i18next.
If we test the context result before destructuring, it will fallback to the other way to get i18next config, and it just works.
Even if it’s not a direct issue in react-i18next, it’s still an issue in the lib usage with React Portal.

**Comment by jamuhl** [comment]
so changing https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L15

to:  `    ? useContext(I18nContext) || {}` should do the trick...

will add that to next version

**Comment by jsomsanith** [comment]
That’s it 🙂
Thank you

**Comment by jamuhl** [comment]
should be in react-i18next@10.11.4
