### ISSUE TITLE
Attempted import error: 'translate' is not exported from 'react-i18next'.

### ISSUE THREAD

**Issue by amit-zen** [i18next/react-i18next#810]
**Describe the bug**
I am following the steps as mentioned in the article below to do a small POC on using i18next in react-
https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-react-app-with-react-i18next

Facing the below error in app.js:
Attempted import error: 'translate' is not exported from 'react-i18next'.

**Occurs in react-i18next version**
    "i18next": "^15.0.8",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-i18next": "^10.6.1",
    "react-scripts": "2.1.8"

[sample zip.zip](https://github.com/i18next/react-i18next/files/3034424/sample.zip.zip)

**Comment by jamuhl** [comment]
what about reading the docs? https://react.i18next.com/latest/migrating-v9-to-v10

or checkout latest sample here https://github.com/i18next/react-i18next/tree/master/example/react

translate was the name in old v8...

**Comment by amit-zen** [comment]
Thank you. Modifying code as per the new version fixed the issue.

**Comment by froston** [comment]
Use `withTranslation()` instead of `translate()` HOC.
Seems like this one is missing in the migration docs.

**Comment by jamuhl** [comment]
@froston https://react.i18next.com/latest/migrating-v9-to-v10#components-v9-greater-than-v10 not sure but in v9 the HOC was named withNamespaces (and we decided to rename it back to withTranslation as while withNamespaces is more correct - most people could make nothing out of the namespaces -> files concept)

**Comment by priyanka2k12** [comment]
Using withTranslation() instead of translate() fixed the issue. Seems like translate() is not in the latest versions.

**Comment by SidOfc** [comment]
It would be cool if `translate` could be added _alongside_ `withNamespaces` to make it clear that either needs to be updated to `withTranslation`. `translate` actually still worked in v9 and the v9 to v10 migration docs say nothing about it though the [v8 CHANGELOG on GitHub](https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#800) shows some change, it's not breaking.

I'm not sure why it hasn't been added yet or how to update the table shown [here](https://react.i18next.com/latest/migrating-v9-to-v10), if someone can point me in the right direction I'm willing to make the change myself so that others may be able to follow the migration docs without issues / having to check GitHub, and you guys can finally stop having to check this "closed" issue.

I suspect more folks doing multiple major version upgrades at once will otherwise end up here as well due to this (easily fixed) inconsistency when they decide to upgrade.

**Comment by jamuhl** [comment]
`translate` had compatibility in v9 (was meant to be removed sooner or later) - than v10 came with a big rewrite making the slow remove with warnings fail out of the door...

https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#800 first line tells `translate ` was renamed to `withTranslation`

hope that change help: https://react.i18next.com/latest/migrating-v9-to-v10

**Comment by SidOfc** [comment]
@jamuhl this is even better than what I had in mind, thank you very much for the quick update! I think this is couldn't be more clear!

Keep up the good work, thanks again 👍
