### ISSUE TITLE
 t function of useTranslation hook recalculated after switch lang

### ISSUE THREAD

**Issue by viclafouch** [i18next/react-i18next#847]
Hello there ! 

I don't know why, but since the last version of react-i18next (I've updated from 10.8.1 to 10.9.0), the `t` function of the hook `UseTranslation` is recalculated after changing the language by doing ` i18n.changeLanguage(langCode)` .. So my useCallback is recalculating...

I need to add a rule to my Eslint, is it normal ? Do you have some solutions ?

![carbon](https://user-images.githubusercontent.com/23353836/57182323-076d4300-6e9e-11e9-8907-a59125720db3.png)

**Comment by jamuhl** [comment]
yes...it's normal and always was like this. You can set https://github.com/i18next/react-i18next/blob/master/src/context.js#L4 like you need in `i18next.init({ react: { bind... }})``

But the problem is more that doing any async fetch should be done in a save way so it does not fetch twice/n-times based on re-render...

**Comment by viclafouch** [comment]
Ok thanks for you answer !
