### ISSUE TITLE
v10 doesn't render values that are React nodes

### ISSUE THREAD

**Issue by pppemo** [i18next/react-i18next#855]
**Describe the bug**
I've recently migrated from `v7.5.1` to `v.10.9.0`. Quite some changes to be made, but I thought I covered it all. However:
When providing `values` object to `<Trans>` component that's values are JSX nodes rather than string/number, the React object doesn't get rendered, but you can see `[object Object]` instead.

**Occurs in react-i18next version**
`"react-i18next": "10.9.0",`

**To Reproduce**
I've got my component that wraps `<Trans>` with some logic, which's `render` method looks like:
```
render() {
  return (
      <Trans
        className="raw-translation"
        count={count}
        i18nKey={id}
        values={values}
      />
  )
}
```

Now given I've got my string to be translated like:
`This is how we {{activity}}`

and that I pass to `<Trans>` component a `values` object that looks:
```
{
  activity: <div>do it</div>
}
```

What I'm getting is: `This is how we [object Object]`

**Expected behaviour**
Expected behaviour would be to get `This is how we do it` or whatever was rendered from the JSX that was the value of `activity`.

**OS (please complete the following information):**
- Device: MBP 2018 15" Mojave 10.14.5
- Browser:
```
Google Chrome | 74.0.3729.169 (Official Build) (64-bit)
-- | --
Revision | 78e4f8db3ce38f6c26cf56eed7ae9b331fc67ada-refs/branch-heads/3729@{#1013}
OS | Mac OS X
JavaScript | V8 7.4.288.28
```

**Additional context**
Same happens when instead of `<div>` I use any other React component - which actually is my case. That used to work in previous version, however the documentation states that `values` property is an object, but it doesn't specify what type its values would be. Thus I was assuming these could be any.

**Comment by jamuhl** [comment]
hm...strange that ever worked before...if so that's more luck than planned ;)

values were meant to be interpolated into it like eg. `activity: <div>do it {{ value }}</div>` given `<Trans values={{ value: 'something' }}`>...`

So in short interpolating components was not meant to be supported. Not saying it's not doable...

I guess the change making it not work for you is here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L98 doing the interpolation step before replacing components -> values are in the combinedTOptions: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L112 so your activity will be interpolated here: https://github.com/i18next/i18next/blob/master/src/Interpolator.js#L117 so will be converted to string.

not sure if something like this works:

```js
render() {
  return (
      <Trans
        className="raw-translation"
        count={count}
        i18nKey={id}
        components={[<div>do it</div>]}
      />
  )
}

where the string is: "This is how we <0></0>"
```

**Comment by pppemo** [comment]
Yup, I guess that would work, but on my side that would require changing all the strings, to be using `<0></0>` instead of `{{activity}}`.

What I did and worked, was the way I invoke that particular functional component, where I actually treat it as a function, rather than component per se. Meaning:
```
      <Trans
        className="raw-translation"
        count={count}
        i18nKey={id}
        values={{
            activity: FormattedDate({ date })
        }}
      />
```

instead of:

```
      <Trans
        className="raw-translation"
        count={count}
        i18nKey={id}
        values={{
            activity: <FormattedDate date={date} />
        }}
      />
```

Thanks!

**Comment by gorhawk** [comment]
Maybe this should be mentioned in the docs. Maybe it wasn't intended, but it seems to me that people use it a lot. I mean we have whole projects using `Hello {{foo}}!` in translations with components.
