### ISSUE TITLE
Translations inconsistent

### ISSUE THREAD

**Issue by developdeez** [i18next/react-i18next#881]
I recently updated versions and have noticed my home page which used to show the translations instantly now shows the keys. I hit refresh and it works but not sure what changed to cause this behavior.

**Comment by jamuhl** [comment]
if a refresh fixes it makes not much sense to me -> where is the difference between a initial load and a refresh load...both are full loads as long no caching is done...

**Comment by developdeez** [comment]
I'm not sure. But it happens regularly. Maybe it's a loading issue. If I find out how to reproduce it on purpose, I will post here.

**Comment by developdeez** [comment]
I can't figure it out. If anyone finds a solution let me know. 

I test by using toast or alert on my home page and refreshing. Its seems as if the root page displays beofr etranslation is able to take place. It's a race condition I think

**Comment by paulogc** [comment]
I'm having a similar issue here after update the lib version. Seems like the component is being loaded before the initialisation finish even wait is set true.

Some more information I'm using the follow versions:
react-i18next: 10.11.2
i18next: 17.0.4

And the plugin:
i18next-browser-languagedetector: 3.0.1

Also I'm adding the resource bundles using callback, what I have noticed is that when the app first render, the resources addition did not finish, so the keys are displayed instead.

**Comment by jamuhl** [comment]
v10 uses suspense -> there is no component rendering `null` in the HOC while loading!!! that's why it's a breaking version -> useSuspense or read how to use it without suspense but do not expect v10 to be like v9

**Comment by paulogc** [comment]
Yeah I can see it, what I'm trying to do is to render the app only when the resource bundler is loaded but I got the follow scenarios using suspense or not:

When using suspense the initialise but because I'm using the callback to add the resource bundle, when I18n ready, the resource bundle still not loaded.

When not using suspense, even I18n ready is true, the same thing happens and keys are not being replaced.

**Comment by jamuhl** [comment]
@paulogc hard to understand for me what you are doing by just reading your text...could you please provide a minimal sample on codesandbox to reproduce?

**Comment by paulogc** [comment]
https://codesandbox.io/embed/youthful-cookies-xrsz1

@jamuhl strange that I could not reproduce in the codesandbox, the structure is something similar to this, the problem when I run my project is that when `i18nProps.hasResourceBundle(i18nProps.language, "common")` it not always return true even `ready` is true. But seems to be something in my side, if you have any idea what could be will be nice. Thanks.

**Comment by jamuhl** [comment]
@paulogc the ready logic goes rather deep into the loading mechanism - it will check not only if resources are loaded - but will also check if there was a try to load them which failed and go into ready state in this case (if at least the fallback was loaded - if I remember right) - this is to avoid endless unreadyness

**Comment by paulogc** [comment]
@jamuhl  what I think is happening, when the app renders, even when `ready` resources are not loaded neither fallback, I know looks weird because I couldn't reproduce in the codesanbox, but there is hard to simulate my scenario with lower connection I got this after debugging my project.

Is there other efficient way to check if resource finish to load?

**Comment by jamuhl** [comment]
@paulogc what we do internal: https://github.com/i18next/react-i18next/blob/master/src/utils.js#L43 not sure but I see no case we might have missed - so would be awesome to get that isolated

**Comment by paulogc** [comment]
@jamuhl after debugging I could see the follow scenario, important details are, I'm not using backend to load translations, I am adding the resource bundle after the init at the init callback via `addResourceBundle` because I need the language detected to import only the file I need.

I always reach this condition `if (!i18n.services.backendConnector.backend) return true;` at the method `hasLoadedNamespace` because my backend is null.

**Comment by jamuhl** [comment]
because I need the language detected to import only the file I need ---> backends do that too

that's because not using a backend we believe you're passing translations on init via options resources ---> there is no way for us to hook into your custom loading process when circumventing the backend.

**Comment by developdeez** [comment]
@jamuhl Is there a call I can make to tell if the translation is ready?
I identified a fix in part of code. Im using shouldComponentRerender and since translation happens after rendering in some cases since updating, it misses it's translation. shouldComponentRerender then prevents it from rerendering with the words since it doesn't know anything changed.

**Comment by developdeez** [comment]
Worse case I could compare pastProps.t("key") with nextProps.t("key") but this seems like a hack

**Comment by paulogc** [comment]
@jamuhl as you said, resolved the problem using  backend plugin to dynamically import the files I need.
Thanks for your support.
