### ISSUE TITLE
AOT (Ahead-Of-Time) compilation with translations pre built.

### ISSUE THREAD

**Issue by cafesanu** [i18next/react-i18next#903]
**Is your feature request related to a problem? Please describe.**
Hi, first of all, thank you for this repo! Glad to see this exist. Second, I come from the Angular World. One of the things I love about it is that, besides JIT (just-in-time) translation, they also provide AOT (Ahead-of-Time) compilation.

See this:
- https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app
- and this... https://medium.com/i18n-and-l10n-resources-for-developers/angular-translation-a-closer-look-at-angular-8-fdf688f3c44a

This allows us to basically have pre-build apps in different languages where you can serve the application based on language (and redirect, for example, via Nginx). The main advantage is that the app doesn't have to continuously calculate the language word(s), and there is no need to have a translation file at all, which is really cool, as this file can be huge (even with lazy loading) when you have a huge app. Also, at least in Angular, with JIT sometimes you see a bit of flickering. AOT also solves this problem.

**Describe the solution you'd like**
So I was wondering if there is something like this in your roadmap, where, if you have N languages, you create N apps during compilation, and serve them differently via Nginx or URL based.

**Describe alternatives you've considered**
I have not found so far any reference to AOT translation in React. Maybe it has a different terminology?

**Additional context**

**Comment by jamuhl** [comment]
What should I say - would love to see this too - but like next-i18next I believe this is something the community will have to step in to make it happen. Such a solution will be very dependent on something like babel. https://github.com/gilbsgilbs/babel-plugin-i18next-extract might be a good starting point - instead of extracting one would generate the output files (combined with webpack power).

I personally won't have the time to create something like this...would take me to much time as I'm not very deep into babel and webpack. BUT: Would be awesome to see this happpen...

**Comment by jamuhl** [comment]
closing as out of scope of my time - everyone is free to make this happen
