### ISSUE TITLE
How to make the lang and dir attributes of the html tag reflect the current language?

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [i18next/react-i18next#925]
Hi,

Thank you for this amazing framework,

I use create react app to create my project and I want the lang and dir attributes of the html tag to reflect the current language?

How to do that please?

All the best,
Mohammed

**Comment by MohammedAl-Mahdawi** [comment]
I used [React Helmet](https://github.com/nfl/react-helmet) and put the following in the App.js file and it worked:

```
<Helmet htmlAttributes={{ lang : this.props.i18n.language, dir: this.props.i18n.dir() }}/>
```

Is this ok or is there an i18next way to do this?

**Comment by jamuhl** [comment]
That's ok...or use `i18next.on('languageChanged', (lng) => {document.documentElement.setAttribute('lang', lng);})`

**Comment by MohammedAl-Mahdawi** [comment]
@jamuhl Thanks a lot!

**Comment by yairEO** [comment]
If the user is not allowed to change the language but it derives by other means, then I simply add this line of code to my `i18next` configuration file:

```js
// my configuration
i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources: {
      ...
    },
    ...
  })

document.documentElement.lang = i18n.language.  // <---- this line right here
```

**Comment by Moki-19** [comment]
`i18next.on('languageChanged', (lng) => {document.documentElement.setAttribute('lang', lng);})`

I'm experiencing an issue in Google Chrome with a similar configuration. Google translate seems to rely only on the first value of the lang attribute of the html tag and comparing it to the browser language. If the values are not equal, it asks for translating the page in a popup.

So when the `languageChanged` event is fired, it is already to late for Google Translate to take care of it (even if using `i18next-browser-languagedetector`), and especially if the user language has to be fetched from a server.

I suspect that this is less an issue regarding i18next than an issue due to the single page application architecture. Does anyone knows how to fix it ?

**Comment by Nsquik** [comment]
@llemaitre19 how did you fix that?

**Comment by llemaitre19** [comment]
@Nsquik , I ended by disabling entirely Google Translate for our web application :
```
<!DOCTYPE html>
<html lang="en" class="notranslate" translate="no">
  <head>
    <meta name="google" content="notranslate" />
  </head>
</html>
```
