### ISSUE TITLE
ComponentType is not assignable to parameter of type ComponentClass

### ISSUE THREAD

**Issue by basslagter** [i18next/react-i18next#938]
When passing withTranslation() hoc to React routers withRouter() I got a typescript error about "ComponentType is not assignable to parameter of type ComponentClass" which seem to be related to this piece of code, which indeed returns React.ComponentType instead of React.ComponentClass. Making this change on my local machine resolved the issue.

```
export interface WithTranslation extends i18next.WithT {
  i18n: i18next.i18n;
  tReady: boolean;
}
export function withTranslation(
  ns?: Namespace,
  options?: {
    withRef?: boolean;
  },
): <P extends WithTranslation>(
  component: React.ComponentType<P>,
) => React.ComponentType<Omit<P, keyof WithTranslation>>;
```

This issue was introduced when upgrading from Typescript 3.5.3 to the newest 3.6.2.

**Comment by rosskevin** [comment]
@basslagter please include your actual errors.

**Comment by basslagter** [comment]
That is "ComponentType<> is not assignable to parameter of type ComponentClass<>"  (i removed some project specific types between the <>

**Comment by rosskevin** [comment]
There is specifically an error number which usually helps with diagnosis and searches, such as TS-xxxx

**Comment by rosskevin** [comment]
@basslagter the `withRouter` definition must be incorrect.

Explanation:
- `React.ComponentType` means class or function (hook): `type ComponentType<P = {}> = ComponentClass<P> | FunctionComponent<P>;` 
- the `react-i18next` implementation is actually returning a `FunctionComponent`

Therefore I could update the signature to return `FunctionComponent` instead of `ComponentType`, but you would still have the problem because whatever `withRouter` definition you are using should accept both `class` and `function`, therefore it should be `React.ComponentType`.

**Comment by basslagter** [comment]
Fair enough...will make an issue there.  Thanks!
