### ISSUE TITLE
Multiple languages in same file

### ISSUE THREAD

**Issue by keerthinathganjam** [i18next/react-i18next#970]
Is there a way i can define translations in same file with defining key just once

Eg:

{
   "Key": ["tran for lang 1", "tran for lang 2", "tran for lang 3"]
}

i have seen below way , but no the above way.

{
     "lang1" : { "key" : "tran for lang1},
     "lang2" : { "key" : "tran for lang2},
     "lang3" : { "key" : "tran for lang3},
}

**Comment by jamuhl** [comment]
both ways described do not work...https://www.i18next.com/how-to/add-or-load-translations

**Comment by jamuhl** [comment]
Why you would prefer that format? Looks rather impractical to me...both for devs and translators...

**Comment by keerthinathganjam** [comment]
Earlier was using some other library which is using the above said format, now to use the same translation file i was looking for these kind of a translation.

**Comment by jamuhl** [comment]
should be easy to convert it from that format to the one needed in i18next

**Comment by angel-langdon** [comment]
@jamuhl 

I think multiple languages in the same file would be the best format because If you have one file for each language you end up with lots of duplications:

- Repeated `index.js` for each language
- Repeated file s for each language
- Repeated translation keys for each language

All this duplicity leads to very slow refactors, changing language strings is  very slow (you have to open on file for each language). Creating a new language is very slow, you have to duplicate all tree structure. 

If you had one file for each language you just simply had to create a new key for a new language ( much more simpler)

Also, doing this approach of one file for each language you are violating one of the most fundamental programming principles (DRY) https://en.wikipedia.org/wiki/Don%27t_repeat_yourself 

:(

**Comment by jamuhl** [comment]
@angel-langdon like said before...i18next is flexible enough so you can for sure pipe your file using some conversion into the resource store....

but we won't use that as default as:

- it leads to bigger bundle sizes if bundled - or can't be downloaded as needed (per language)
- does not help translators to work more efficient
- it's harder to maintain with more than one person working on translations

Thanks for the hint that we violate a core principle...shame on us ;)

**Comment by angel-langdon** [comment]
@jamuhl Thank you for your response, It's an amazing library don't get me wrong :) . I am possibly wrong... I am not so expert as you are

> it leads to bigger bundle sizes if bundled - or can't be downloaded as needed (per language)
A compiler could handle this stuff, programmer and translator time are more valuable

> does not help translators to work more efficient
There could be lots of optimisations/abstractions to improve translation time

> it's harder to maintain with more than one person working on translations
There could abstractions so it is not harder to maintain but I don't really think that is a very big problem. In most cases translations are just done one time

> is flexible enough so you can for sure pipe your file using some conversion into the resource store....
We are going to stick with with your folder structure anyways because it's more popular

Again, thank you for your response!
