### ISSUE TITLE
Add localsubpath to url in react-i18next like in next-i18next

### ISSUE THREAD

**Issue by shakesBeardZ** [i18next/react-i18next#971]
(I know it's not the right place but no one answered me in stackoverflow)
I'm trying to show the current language in the URL when using react-i18next like: example.com/en , I'm used to that in next-i18next, example:

```
new NextI18Next({
  localeSubpaths: {
    fr: 'fr',
    de: 'german',
    en: 'eng',
  }
})
```

**Comment by jamuhl** [comment]
Please head over to the right repo with this question: https://github.com/isaachinman/next-i18next

**Comment by shakesBeardZ** [comment]
@jamuhl I'm using this library this why I posted the question here, so if you have the answer answer me and if you don't have don't tell me what to do, there is people in the community can answer such questions. or share their experience in solving similar issues.

**Comment by jamuhl** [comment]
`localSubpaths` are not part of react-i18next ---> it's part of next-i18next's options -> that's why I don't have the answer nor you will get an answer here ---> the people on next-i18next will help you...put if you do not like to be directed to the right module...idk...just wanted to help you find the right place for your question...
